name: Start ovhai job container
on:
  schedule:
    - cron:  '0 5 * * *'

env:
  OVH_REGION: GRA
  TAG: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install ovhai command
        run: |
          wget https://cli.${{ env.OVH_REGION }}.training.ai.cloud.ovh.net/ovhai-linux.zip
          unzip ovhai-linux.zip
          mkdir -p $HOME/bin
          mv ovhai $HOME/bin/ovhai
          echo "$PATH:$HOME/bin/" >> $GITHUB_PATH
      - name: Login to ovhai
        run: |
          ovhai login -p ${{ secrets.OVH_PSWD }} -u ${{ secrets.OVH_USER }}
      - name: Deploy to ovhai
        id: deploy
        run: |
          ovhai job run --default-http-port 8000 --cpu 4 -o json ghcr.io/datalab-mi/cclabeler:${{ env.TAG }}-cli > job.json
          echo "::set-output name=OVH_JOB_ID::$(cat job.json | jq -r '.id')"
      - name: get url
        run: echo https://${{ steps.deploy.outputs.OVH_JOB_ID }}.job.gra.training.ai.cloud.ovh.net
      - name: persist job url
        run: |
          curl -X POST \
          -H 'x-api-key: ${{ secrets.PERSISTENT_VALUE_ACCESS_TOKEN }}' \
          -H 'x-github-repo: https://github.com/datalab-mi/cclabeler' \
          -H 'content-type: application/json' \
          -d '{ "value": "${{ steps.deploy.outputs.OVH_JOB_ID }}" }' \
          'https://persistent.aaim.io/api/values/set?key=OVH_JOB_ID&output=plain'
